config/routes.rb
Rails.application.routes.draw do
  resources :filhotes
  resources :ninhadas
  resources :padreadores
  resources :matrizes
  resources :caracteristicas
  resources :racas

  devise_for :usuarios do
    get '/usuarios/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => redirect('/singleview')

  # view routes
  get '/singleview' => 'singleview#index'

  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

end

app/models/ninhada.rb
class Ninhada < ApplicationRecord
  belongs_to :matriz
  belongs_to :padreador
  has_many :filhotes
  enum parto: { normal: 1, cesaria: 2}
  enum situacao: { gestante: 1, nascido: 2, perdido: 3}
end

app/controllers/ninhadas_controller.rb
class NinhadasController < ApplicationController
  before_action :set_ninhada, only: [:show, :edit, :update, :destroy]
  before_action :set_matrizes, only: [:edit, :update, :new]
  before_action :set_padreadores, only: [:edit, :update, :new]
  before_action :authenticate_usuario!

  # GET /ninhadas
  # GET /ninhadas.json
  def index
    @ninhadas = Ninhada.all
  end

  # GET /ninhadas/1
  # GET /ninhadas/1.json
  def show
  end

  # GET /ninhadas/new
  def new
    @ninhada = Ninhada.new
  end

  # GET /ninhadas/1/edit
  def edit
  end

  # POST /ninhadas
  # POST /ninhadas.json
  def create
    @ninhada = Ninhada.new(ninhada_params)

    respond_to do |format|
      if @ninhada.save
        format.html { redirect_to @ninhada, notice: 'Ninhada was successfully created.' }
        format.json { render :show, status: :created, location: @ninhada }
      else
        format.html { render :new }
        format.json { render json: @ninhada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ninhadas/1
  # PATCH/PUT /ninhadas/1.json
  def update
    respond_to do |format|
      if @ninhada.update(ninhada_params)
        format.html { redirect_to @ninhada, notice: 'Ninhada was successfully updated.' }
        format.json { render :show, status: :ok, location: @ninhada }
      else
        format.html { render :edit }
        format.json { render json: @ninhada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ninhadas/1
  # DELETE /ninhadas/1.json
  def destroy
    @ninhada.destroy
    respond_to do |format|
      format.html { redirect_to ninhadas_url, notice: 'Ninhada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ninhada
      @ninhada = Ninhada.find(params[:id])
    end
    def set_matrizes
      @matrizes = Matriz.all
    end
    def set_padreadores
      @padreadores = Padreador.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ninhada_params
      params.require(:ninhada).permit(:nome, :quantidade_vivo, :quantidade_falecido, :parto, :situacao, :observacao, :matriz_id, :padreador_id)
    end
end

app/helpers/ninhadas_helper.rb
module NinhadasHelper
end

app/views/ninhadas/_form.html.slim
= simple_form_for @ninhada do |f|
  - if @ninhada.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ninhada.errors.count, "error")} prohibited this ninhada from being saved:"
      ul
        - @ninhada.errors.full_messages.each do |message|
          li = message

  .card.card-default
    .card-body
      .form-group
        .row
          .col-md-12
            = f.label :nome
            = f.text_field :nome, class:"form-control", placeholder:"Nome"
      .form-group
        .row
          .col-md-3
            = f.label :quantidade_vivo
            = f.number_field :quantidade_vivo, class:"form-control"
          .col-md-3
            = f.label :quantidade_falecido
            = f.number_field :quantidade_falecido, class:"form-control"
          .col-md-3
            = f.input :parto, collection: Ninhada.partos, prompt: false
          .col-md-3
            = f.input :situacao, collection: Ninhada.situacoes, prompt: false
      .form-group
        .row
          .col-md-3
            = f.label :matriz_id
            = f.collection_select(:matriz_id, @matrizes, :id, :nome, include_blank: true)
          .col-md-3
            = f.label :padreador_id
            = f.collection_select(:padreador_id, @padreadores, :id, :nome, include_blank: true)
          .col-md-3
            = f.label :data_cruzamento
            = f.date_field :data_cruzamento, class:"form-control"
          .col-md-3
            = f.label :previsao_nascimento
            = f.date_field :previsao_nascimento, class:"form-control"
      .form-group
        .row
          .col-md-12
            = f.label :observacao
            = f.text_area(:observacao, cols: 100, rows: 5, class:"form-control")

  .form-group
    .row
      .col-md-3
        .actions
          = f.button :submit, class: "btn btn-oval btn-success"

app/views/ninhadas/edit.html.slim
h1 Editing ninhada

== render 'form'

=> link_to 'Show', @ninhada
'|
=< link_to 'Back', ninhadas_path

app/views/ninhadas/index.html.slim
.card.card-default
  .card-header
    h2 Ninhadas
  .card-body
    /! START table-responsive
    .table-responsive
      table.table
        thead
          tr
            th Nome
            th Qtde vivos
            th Qtde falecidos
            th Parto
            th Situação
            th Observação
            th Matriz
            th Padreador
            th
            th

        tbody
          - @ninhadas.each do |ninhada|
            tr
              td = ninhada.nome
              td = ninhada.quantidade_vivo
              td = ninhada.quantidade_falecido
              td = ninhada.parto
              td = ninhada.situacao
              td = ninhada.observacao
              td = ninhada.matriz.nome
              td = ninhada.padreador.nome
              td = link_to edit_ninhada_path(ninhada), class:"btn btn-oval btn-primary" do
                em.fa-1x.mr-1.far.fa-edit
              td = link_to ninhada, method: :delete, class:"btn btn-oval btn-danger", data: { confirm: 'Are you sure?' } do
                em.fa-1x.mr-1.fas.fa-minus-circle
= link_to new_ninhada_path,  class:"btn btn-oval btn-success" do
  em.fa-1x.mr-1.fas.fa-plus

app/views/ninhadas/new.html.slim
h2 Cadastrar Ninhada

== render 'form'

.actions
  = link_to "Voltar", ninhadas_path, class: "btn btn-oval btn-primary"

app/views/ninhadas/show.html.slim
p#notice = notice

p
  strong Nome:
  = @ninhada.nome
p
  strong Quantidade vivo:
  = @ninhada.quantidade_vivo
p
  strong Quantidade falecido:
  = @ninhada.quantidade_falecido
p
  strong Parto:
  = @ninhada.parto
p
  strong Situacao:
  = @ninhada.situacao
p
  strong Observacao:
  = @ninhada.observacao
p
  strong Matriz:
  = @ninhada.matriz_id
p
  strong Padreador:
  = @ninhada.padreador_id

=> link_to 'Edit', edit_ninhada_path(@ninhada)
'|
=< link_to 'Back', ninhadas_path