config/routes.rb
Rails.application.routes.draw do
  resources :filhotes
  resources :ninhadas
  resources :padreadores
  resources :matrizes
  resources :caracteristicas
  resources :racas

  devise_for :usuarios do
    get '/usuarios/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => redirect('/singleview')

  # view routes
  get '/singleview' => 'singleview#index'

  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

end

app/models/matriz.rb
class Matriz < ApplicationRecord
  belongs_to :raca
  belongs_to :caracteristica
  has_one_attached :avatar
  has_many :ninhadas
  has_many :filhotes
  validates_presence_of :nome, :data_nascimento
  attr_default :falecido, false
end

app/controllers/matrizes_controller.rb
class MatrizesController < ApplicationController
  before_action :set_matriz, only: [:show, :edit, :update, :destroy]
  before_action :set_racas, only: [:edit, :update, :new]
  before_action :set_caracteristicas, only: [:edit, :update, :new]
  before_action :authenticate_usuario!

  # GET /matrizes
  # GET /matrizes.json
  def index
    @matrizes = Matriz.all
  end

  # GET /matrizes/1
  # GET /matrizes/1.json
  def show
  end

  # GET /matrizes/new
  def new
    @matriz = Matriz.new
  end

  # GET /matrizes/1/edit
  def edit
  end

  # POST /matrizes
  # POST /matrizes.json
  def create
    @matriz = Matriz.new(matriz_params)

    respond_to do |format|
      if @matriz.save
        format.html { redirect_to @matriz, notice: 'Matriz was successfully created.' }
        format.json { render :show, status: :created, location: @matriz }
      else
        format.html { render :new }
        format.json { render json: @matriz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matrizes/1
  # PATCH/PUT /matrizes/1.json
  def update
    respond_to do |format|
      if @matriz.update(matriz_params)
        format.html { redirect_to @matriz, notice: 'Matriz was successfully updated.' }
        format.json { render :show, status: :ok, location: @matriz }
      else
        format.html { render :edit }
        format.json { render json: @matriz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matrizes/1
  # DELETE /matrizes/1.json
  def destroy
    @matriz.destroy
    respond_to do |format|
      format.html { redirect_to matrizes_url, notice: 'Matriz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matriz
      @matriz = Matriz.find(params[:id])
    end
    def set_racas
      @racas = Raca.all
    end
    def set_caracteristicas
      @caracteristicas = Caracteristica.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matriz_params
      params.require(:matriz).permit(:nome, :data_nascimento, :falecido, :raca_id, :caracteristica_id, :avatar)
    end
end

app/helpers/matrizes_helper.rb
module MatrizesHelper
end

app/views/matrizes/_form.html.slim
= simple_form_for @matriz do |f|
  - if @matriz.errors.any?
    #error_explanation
      h2 = "#{pluralize(@matriz.errors.count, "error")} prohibited this matriz from being saved:"
      ul
        - @matriz.errors.full_messages.each do |message|
          li = message

  .card.card-default
    .card-body
      .form-group
        .row
          .col-md-12
            = f.label :nome
            = f.text_field :nome, class:"form-control", placeholder:"Nome"
      .form-group
        .row
          .col-md-4
            = f.label :data_nascimento
            = f.date_field :data_nascimento, class:"form-control"
          .col-md-4
            = f.label :raca_id
            = f.collection_select(:raca_id, @racas, :id, :nome, include_blank: true, class:"chosen-container chosen-container-single")
          .col-md-4
            = f.label :caracteristica_id
            = f.collection_select(:caracteristica_id, @caracteristicas, :id, :nome, include_blank: true)
      .form-group
        .row
          .col-md-4
            = f.input :falecido
        .row
          .col-md-8
            = f.label :avatar
            = f.file_field :avatar, class:"field"

  .form-group
    .row
      .col-md-3
        .actions
          = f.button :submit, class: "btn btn-oval btn-success"

app/views/matrizes/edit.html.slim
h1 Editing matriz

== render 'form'

=> link_to 'Show', @matriz
'|
=< link_to 'Back', matrizes_path

app/views/matrizes/index.html.slim
.card.card-default
  .card-header
    h2 Matrizes
  .card-body
    /! START table-responsive
    .table-responsive
      table.table
        thead
          tr
            th Nome
            th Data de Nascimento
            th Raça
            th Característica
            th
            th

        tbody
          - @matrizes.each do |matriz|
            tr
              td = matriz.nome
              td = l(matriz.data_nascimento)
              td = matriz.raca.nome
              td = matriz.caracteristica.nome
              td = link_to edit_matriz_path(matriz), class:"btn btn-oval btn-primary" do
                em.fa-1x.mr-1.far.fa-edit
              td = link_to matriz_path(matriz), class:"btn btn-oval btn-primary" do
                em.fa-1x.mr-1.far.fa-view
              td = link_to matriz, method: :delete, class:"btn btn-oval btn-danger", data: { confirm: 'Are you sure?' } do
                em.fa-1x.mr-1.fas.fa-minus-circle
= link_to new_matriz_path,  class:"btn btn-oval btn-success" do
  em.fa-1x.mr-1.fas.fa-plus

app/views/matrizes/new.html.slim
h2 Cadastrar Matriz

== render 'form'

.actions
  = link_to "Voltar", matrizes_path, class: "btn btn-oval btn-primary"

app/views/matrizes/show.html.slim
p#notice = notice

p
  strong Nome:
  = @matriz.nome
p
  strong Data nascimento:
  = l(@matriz.data_nascimento)
p
  strong Falecido:
  = @matriz.falecido
p
  strong Raca:
  = @matriz.raca.nome
p
  strong Caracteristica:
  = @matriz.caracteristica.nome
  p
    strong Avatar:
    = image_tag @matriz.avatar

=> link_to 'Edit', edit_matriz_path(@matriz)
'|
=< link_to 'Back', matrizes_path