config/routes.rb
Rails.application.routes.draw do
  resources :filhotes
  resources :ninhadas
  resources :padreadores
  resources :matrizes
  resources :caracteristicas
  resources :racas

  devise_for :usuarios do
    get '/usuarios/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => redirect('/singleview')

  # view routes
  get '/singleview' => 'singleview#index'

  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

end

app/models/filhote.rb
class Filhote < ApplicationRecord
  belongs_to :raca
  belongs_to :caracteristica
  belongs_to :matriz
  belongs_to :padreador
  belongs_to :ninhada
  has_one_attached :avatar
  attr_default :disponivel, true
end

app/controllers/filhotes_controller.rb
class FilhotesController < ApplicationController
  before_action :set_filhote, only: [:show, :edit, :update, :destroy]
  before_action :set_matrizes, only: [:edit, :update, :new]
  before_action :set_padreadores, only: [:edit, :update, :new]
  before_action :set_racas, only: [:edit, :update, :new]
  before_action :set_caracteristicas, only: [:edit, :update, :new]
  before_action :set_ninhadas, only: [:edit, :update, :new]
  before_action :authenticate_usuario!

  # GET /filhotes
  # GET /filhotes.json
  def index
    @filhotes = Filhote.all
  end

  # GET /filhotes/1
  # GET /filhotes/1.json
  def show
  end

  # GET /filhotes/new
  def new
    @filhote = Filhote.new
  end

  # GET /filhotes/1/edit
  def edit
  end

  # POST /filhotes
  # POST /filhotes.json
  def create
    @filhote = Filhote.new(filhote_params)

    respond_to do |format|
      if @filhote.save
        format.html { redirect_to @filhote, notice: 'Filhote was successfully created.' }
        format.json { render :show, status: :created, location: @filhote }
      else
        format.html { render :new }
        format.json { render json: @filhote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filhotes/1
  # PATCH/PUT /filhotes/1.json
  def update
    respond_to do |format|
      if @filhote.update(filhote_params)
        format.html { redirect_to @filhote, notice: 'Filhote was successfully updated.' }
        format.json { render :show, status: :ok, location: @filhote }
      else
        format.html { render :edit }
        format.json { render json: @filhote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filhotes/1
  # DELETE /filhotes/1.json
  def destroy
    @filhote.destroy
    respond_to do |format|
      format.html { redirect_to filhotes_url, notice: 'Filhote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filhote
      @filhote = Filhote.find(params[:id])
    end
    def set_matrizes
      @matrizes = Matriz.all
    end
    def set_padreadores
      @padreadores = Padreador.all
    end
    def set_racas
      @racas = Raca.all
    end
    def set_caracteristicas
      @caracteristicas = Caracteristica.all
    end
    def set_ninhadas
      @ninhadas = Ninhada.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def filhote_params
      params.require(:filhote).permit(:nome, :data_nascimento, :preco, :disponivel, :raca_id, :caracteristica_id, :matriz_id, :padreador_id, :ninhada_id, :avatar)
    end
end

app/helpers/filhotes_helper.rb
module FilhotesHelper
end

app/views/filhotes/_form.html.slim
= simple_form_for @filhote do |f|
  - if @filhote.errors.any?
    #error_explanation
      h2 = "#{pluralize(@filhote.errors.count, "error")} prohibited this filhote from being saved:"
      ul
        - @filhote.errors.full_messages.each do |message|
          li = message

  .card.card-default
    .card-body
      .form-group
        .row
          .col-md-12
            = f.label :nome
            = f.text_field :nome, class:"form-control", placeholder:"Nome"
      .form-group
        .row
          .col-md-3
            = f.label :data_nascimento
            = f.date_field :data_nascimento, class:"form-control"
          .col-md-3
            = f.label :preco
            = f.text_field :preco, class:"form-control"
          .col-md-3
            = f.label :ninhada_id
            = f.collection_select(:ninhada_id, @ninhadas, :id, :nome, include_blank: true)
          .col-md-3
            = f.label :disponivel
            = f.check_box :disponivel
      .form-group
        .row
          .col-md-3
            = f.label :raca_id
            = f.collection_select(:raca_id, @racas, :id, :nome, include_blank: true)
          .col-md-3
            = f.label :caracteristica_id
            = f.collection_select(:caracteristica_id, @caracteristicas, :id, :nome, include_blank: true)
          .col-md-3
            = f.label :matriz_id
            = f.collection_select(:matriz_id, @matrizes, :id, :nome, include_blank: true)
          .col-md-3
            = f.label :padreador_id
            = f.collection_select(:padreador_id, @padreadores, :id, :nome, include_blank: true)
        .row
          .col-md-12
            = f.label :avatar
            = f.file_field :avatar, class:"field"
  .form-group
    .row
      .col-md-3
        .actions
          = f.button :submit, class: "btn btn-oval btn-success"

app/views/filhotes/edit.html.slim
h1 Editing filhote

== render 'form'

=> link_to 'Show', @filhote
'|
=< link_to 'Back', filhotes_path

app/views/filhotes/index.html.slim
.card.card-default
  .card-header
    h2 Filhotes
  .card-body
    /! START table-responsive
    .table-responsive
      table.table
        thead
          tr
            th Nome
            th Data de Nascimento
            th Preço
            th Disponível
            th Raça
            th Característica
            th Matriz
            th Padreador
            th Ninhada
            th
            th

        tbody
          - @filhotes.each do |filhote|
            tr
              td = filhote.nome
              td = l(filhote.data_nascimento)
              td = filhote.preco
              td = filhote.disponivel
              td = filhote.raca.nome
              td = filhote.caracteristica.nome
              td = filhote.matriz.nome
              td = filhote.padreador.nome
              td = filhote.ninhada.nome
              td = link_to edit_filhote_path(filhote), class:"btn btn-oval btn-primary" do
                em.fa-1x.mr-1.far.fa-edit
              td = link_to filhote, method: :delete, class:"btn btn-oval btn-danger", data: { confirm: 'Are you sure?' } do
                em.fa-1x.mr-1.fas.fa-minus-circle
= link_to new_filhote_path,  class:"btn btn-oval btn-success" do
  em.fa-1x.mr-1.fas.fa-plus

app/views/filhotes/new.html.slim
h2 Cadastro de Filhote

== render 'form'

.actions
  = link_to "Voltar", filhotes_path, class: "btn btn-oval btn-primary"

app/views/filhotes/show.html.slim
p#notice = notice

p
  strong Nome:
  = @filhote.nome
p
  strong Data nascimento:
  = l(@filhote.data_nascimento)
p
  strong Preco:
  = @filhote.preco
p
  strong Disponivel:
  = @filhote.disponivel
p
  strong Raca:
  = @filhote.raca.nome
p
  strong Caracteristica:
  = @filhote.caracteristica.nome
p
  strong Matriz:
  = @filhote.matriz.nome
p
  strong Padreador:
  = @filhote.padreador.nome
p
  strong Ninhada:
  = @filhote.ninhada.nome
p
  strong Avatar:
  = image_tag @filhote.avatar

=> link_to 'Edit', edit_filhote_path(@filhote)
'|
=< link_to 'Back', filhotes_path