config/routes.rb
Rails.application.routes.draw do
  resources :filhotes
  resources :ninhadas
  resources :padreadores
  resources :matrizes
  resources :caracteristicas
  resources :racas

  devise_for :usuarios do
    get '/usuarios/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  root :to => redirect('/singleview')

  # view routes
  get '/singleview' => 'singleview#index'

  # api routes
  get '/api/i18n/:locale' => 'api#i18n'

end

app/views/layouts/partials/_footer.html.slim
span © 2020 - Angle

app/views/layouts/partials/_offsidebar.html.slim
/! START Off Sidebar (right)
nav
  div role="tabpanel"
    /! Nav tabs
    ul.nav.nav-tabs.nav-justified role="tablist"
      li.nav-item role="presentation"
        a.nav-link.active aria-controls="app-settings" data-toggle="tab" href="#app-settings" role="tab"
          em.icon-equalizer.fa-lg
      li.nav-item role="presentation"
        a.nav-link aria-controls="app-chat" data-toggle="tab" href="#app-chat" role="tab"
          em.icon-user.fa-lg
    /! Tab panes
    .tab-content
      #app-settings.tab-pane.fade.active.show role="tabpanel"
        h3.text-center.text-thin.mt-4 Settings
        .p-2
          h4.text-muted.text-thin Themes
          .row.row-flush.mb-2
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-a.css')}"
                  input checked="checked" name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-info
                    span.color.bg-info-light
                  span.color.bg-white
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-b.css')}"
                  input name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-green
                    span.color.bg-green-light
                  span.color.bg-white
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-c.css')}"
                  input name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-purple
                    span.color.bg-purple-light
                  span.color.bg-white
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-d.css')}"
                  input name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-danger
                    span.color.bg-danger-light
                  span.color.bg-white
          .row.row-flush.mb-2
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-e.css')}"
                  input name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-info-dark
                    span.color.bg-info
                  span.color.bg-gray-dark
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-f.css')}"
                  input name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-green-dark
                    span.color.bg-green
                  span.color.bg-gray-dark
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-g.css')}"
                  input name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-purple-dark
                    span.color.bg-purple
                  span.color.bg-gray-dark
            .col.mb-2
              .setting-color
                label data-load-css="#{asset_path('angle/themes/theme-h.css')}"
                  input name="setting-theme" type="radio" /
                  span.icon-check
                  span.split
                    span.color.bg-danger-dark
                    span.color.bg-danger
                  span.color.bg-gray-dark
        .p-2
          h4.text-muted.text-thin Layout
          .clearfix
            p.float-left Fixed
            .float-right
              label.switch
                input#chk-fixed data-toggle-state="layout-fixed" type="checkbox" /
                span
          .clearfix
            p.float-left Boxed
            .float-right
              label.switch
                input#chk-boxed data-toggle-state="layout-boxed" type="checkbox" /
                span
        .p-2
          h4.text-muted.text-thin Aside
          .clearfix
            p.float-left Collapsed
            .float-right
              label.switch
                input#chk-collapsed data-toggle-state="aside-collapsed" type="checkbox" /
                span
          .clearfix
            p.float-left Collapsed Text
            .float-right
              label.switch
                input#chk-collapsed-text data-toggle-state="aside-collapsed-text" type="checkbox" /
                span
          .clearfix
            p.float-left Float
            .float-right
              label.switch
                input#chk-float data-toggle-state="aside-float" type="checkbox" /
                span
          .clearfix
            p.float-left Hover
            .float-right
              label.switch
                input#chk-hover data-toggle-state="aside-hover" type="checkbox" /
                span
          .clearfix
            p.float-left Show Scrollbar
            .float-right
              label.switch
                input#chk-scroll data-target=".sidebar" data-toggle-state="show-scrollbar" type="checkbox" /
                span
      #app-chat.tab-pane.fade role="tabpanel"
        h3.text-center.text-thin.mt-4 Connections
        .list-group
          /! START list title
          .list-group-item.border-0
            small.text-muted ONLINE
          /! END list title
          .list-group-item.list-group-item-action.border-0
            .media
              img.align-self-center.mr-3.rounded-circle.thumb48 alt="Image" src="#{image_path('angle/user/05.jpg')}" /
              .media-body.text-truncate
                a href="#"
                  strong Juan Sims
                br/
                small.text-muted Designeer
              .ml-auto
                span.circle.bg-success.circle-lg
          .list-group-item.list-group-item-action.border-0
            .media
              img.align-self-center.mr-3.rounded-circle.thumb48 alt="Image" src="#{image_path('angle/user/06.jpg')}" /
              .media-body.text-truncate
                a href="#"
                  strong Maureen Jenkins
                br/
                small.text-muted Designeer
              .ml-auto
                span.circle.bg-success.circle-lg
          .list-group-item.list-group-item-action.border-0
            .media
              img.align-self-center.mr-3.rounded-circle.thumb48 alt="Image" src="#{image_path('angle/user/07.jpg')}" /
              .media-body.text-truncate
                a href="#"
                  strong Billie Dunn
                br/
                small.text-muted Designeer
              .ml-auto
                span.circle.bg-danger.circle-lg
          .list-group-item.list-group-item-action.border-0
            .media
              img.align-self-center.mr-3.rounded-circle.thumb48 alt="Image" src="#{image_path('angle/user/08.jpg')}" /
              .media-body.text-truncate
                a href="#"
                  strong Tomothy Roberts
                br/
                small.text-muted Designeer
              .ml-auto
                span.circle.bg-warning.circle-lg
          /! START list title
          .list-group-item.border-0
            small.text-muted OFFLINE
          /! END list title
          .list-group-item.list-group-item-action.border-0
            .media
              img.align-self-center.mr-3.rounded-circle.thumb48 alt="Image" src="#{image_path('angle/user/09.jpg')}" /
              .media-body.text-truncate
                a href="#"
                  strong Lawrence Robinson
                br/
                small.text-muted Designeer
              .ml-auto
                span.circle.bg-warning.circle-lg
          .list-group-item.list-group-item-action.border-0
            .media
              img.align-self-center.mr-3.rounded-circle.thumb48 alt="Image" src="#{image_path('angle/user/10.jpg')}" /
              .media-body.text-truncate
                a href="#"
                  strong Tyrone Owens
                br/
                small.text-muted Designeer
              .ml-auto
                span.circle.bg-warning.circle-lg
        .px-3.py-4.text-center
          /! Optional link to list more users
          a.btn.btn-purple.btn-sm href="#" title=("See more contacts")
            strong Load more..
        /! Extra items
        .px-3.py-2
          p
            small.text-muted Tasks completion
          .progress.progress-xs.m-0
            .progress-bar.bg-success aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" style=("width: 80%;")
              span.sr-only 80% Complete
        .px-3.py-2
          p
            small.text-muted Upload quota
          .progress.progress-xs.m-0
            .progress-bar.bg-warning aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" style=("width: 40%;")
              span.sr-only 40% Complete
/! END Off Sidebar (right)

app/views/layouts/partials/_sidebar.html.slim
/! START Sidebar (left)
.aside-inner
  nav.sidebar data-sidebar-anyclick-close=""
    /! START sidebar nav
    ul.sidebar-nav
      /! START user info
      li.has-user-block
        -if usuario_signed_in?
          #user-block.collapse
            .item.user-block
              /! User picture
              .user-block-picture
                .user-block-status
                  img.img-thumbnail.rounded-circle alt="Avatar" height="60" src="#{image_path('angle/user/02.jpg')}" width="60" /
                  .circle.bg-success.circle-lg
              /! Name and Job
              .user-block-info
                span.user-block-name
                  = current_usuario.nome
                = link_to "Sair", '/usuarios/sign_out', :method => :delete
        - else
          = link_to "Logar", usuario_session_path
      li.nav-heading
        span Menu de Navegação
      /! Iterates over all sidebar items
      li
        a data-toggle="collapse" href="#submenu" title="Menu"
          em.icon-note
          span data-localize="sidebar.nav.menu.MENU"  Cadastros
        ul#submenu.sidebar-nav.sidebar-subnav.collapse
          li title="submenu"
            span data-localize="sidebar.nav.menu.SUBMENU"
            = link_to "Raça", racas_path
          li title="submenu"
            span data-localize="sidebar.nav.menu.SUBMENU"
            = link_to "Caracteristicas", caracteristicas_path
          li title="submenu"
            span data-localize="sidebar.nav.menu.SUBMENU"
            = link_to "Matrizes", matrizes_path
          li title="submenu"
            span data-localize="sidebar.nav.menu.SUBMENU"
            = link_to "Padreadores", padreadores_path
          li title="submenu"
            span data-localize="sidebar.nav.menu.SUBMENU"
            = link_to "Ninhada", ninhadas_path
          li title="submenu"
            span data-localize="sidebar.nav.menu.SUBMENU"
            = link_to "Filhote", filhotes_path

        li
          a data-toggle="collapse" href="#submenu3" title="Menu3"
            em.icon-layers
            span data-localize="sidebar.nav.menu.MENU"  Vendas
          ul#submenu3.sidebar-nav.sidebar-subnav.collapse
            li.sidebar-subnav-header Filhotes
            li
              a href="" title="Submenu"
                span data-localize="sidebar.nav.menu.submenu"  Filhotes
            li.sidebar-subnav-header ###
            li
              a href="" title="Submenu"
                span data-localize="sidebar.nav.menu.submenu"  ###

app/views/layouts/partials/_topnavbar.html.slim
/! START Top Navbar
nav.navbar.topnavbar
  /! START navbar header
  .navbar-header
    a.navbar-brand href="#/"
      .brand-logo
        img.img-fluid alt=("App Logo") src="#{image_path('angle/logo.png')}" /
      .brand-logo-collapsed
        img.img-fluid alt=("App Logo") src="#{image_path('angle/logo-single.png')}" /
  /! END navbar header
  /! START Left navbar
  ul.navbar-nav.mr-auto.flex-row
    li.nav-item
      /! Button used to collapse the left sidebar. Only visible on tablet and desktops
      a.nav-link.d-none.d-md-block.d-lg-block.d-xl-block data-toggle-state="aside-collapsed" data-trigger-resize="" href="#"
        em.fas.fa-bars
      /! Button to show/hide the sidebar on mobile. Visible on mobile only.
      a.nav-link.sidebar-toggle.d-md-none data-no-persist="true" data-toggle-state="aside-toggled" href="#"
        em.fas.fa-bars
    /! START User avatar toggle
    li.nav-item.d-none.d-md-block
      /! Button used to collapse the left sidebar. Only visible on tablet and desktops
      a#user-block-toggle.nav-link data-toggle="collapse" href="#user-block"
        em.icon-user
    /! END User avatar toggle
    /! START lock screen
    li.nav-item.d-none.d-md-block
      a.nav-link href="/pages/lock" title=("Lock screen")
        em.icon-lock
    /! END lock screen
  /! END Left navbar
  /! START Right Navbar
  ul.navbar-nav.flex-row
    /! Search icon
    li.nav-item
      a.nav-link data-search-open="" href="#"
        em.icon-magnifier
    /! Fullscreen (only desktops)
    li.nav-item.d-none.d-md-block
      a.nav-link data-toggle-fullscreen="" href="#"
        em.fa.fa-expand
    /! START Alert menu
    li.nav-item.dropdown.dropdown-list
      a.nav-link.dropdown-toggle.dropdown-toggle-nocaret data-toggle="dropdown" href="#"
        em.icon-bell
        span.badge.badge-danger 11
      /! START Dropdown menu
      .dropdown-menu.dropdown-menu-right.animated.flipInX
        .dropdown-item
          /! START list group
          .list-group
            /! list item
            .list-group-item.list-group-item-action
              .media
                .align-self-start.mr-2
                  em.fab.fa-twitter.fa-2x.text-info
                .media-body
                  p.m-0 New followers
                  p.m-0.text-muted.text-sm 1 new follower
            /! list item
            .list-group-item.list-group-item-action
              .media
                .align-self-start.mr-2
                  em.fa.fa-envelope.fa-2x.text-warning
                .media-body
                  p.m-0 New e-mails
                  p.m-0.text-muted.text-sm You have 10 new emails
            /! list item
            .list-group-item.list-group-item-action
              .media
                .align-self-start.mr-2
                  em.fa.fa-tasks.fa-2x.text-success
                .media-body
                  p.m-0 Pending Tasks
                  p.m-0.text-muted.text-sm 11 pending task
            /! last list item
            .list-group-item.list-group-item-action
              span.d-flex.align-items-center
                span.text-sm More notifications
                span.badge.badge-danger.ml-auto 14
          /! END list group
      /! END Dropdown menu
    /! END Alert menu
    /! START Offsidebar button
    li.nav-item
      a.nav-link data-no-persist="true" data-toggle-state="offsidebar-open" href="#"
        em.icon-notebook
    /! END Offsidebar menu
  /! END Right Navbar
  /! START Search form
  form.navbar-form action="search.html" role="search"
    .form-group
      input.form-control placeholder=("Type and hit enter ...") type="text" /
      .fa.fa-times.navbar-form-close data-search-dismiss=""
    button.d-none type="submit"  Submit
  /! END Search form
/! END Top Navbar

app/views/layouts/partials/_topnavbar_h.html.slim
/! START Top Navbar
nav.navbar.topnavbar.navbar-expand-lg.navbar-light
  /! START navbar header
  .navbar-header
    a.navbar-brand href="#/"
      .brand-logo
        img.img-fluid alt=("App Logo") src="#{image_path('angle/logo.png')}" /
      .brand-logo-collapsed
        img.img-fluid alt=("App Logo") src="#{image_path('angle/logo-single.png')}" /
    button.navbar-toggler data-target="#topnavbar" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
  /! END navbar header
  /! START Nav wrapper
  #topnavbar.navbar-collapse.collapse
    /! START Left navbar
    ul.nav.navbar-nav.mr-auto.flex-column.flex-lg-row
      li.nav-item.dropdown
        a.nav-link.dropdown-toggle.dropdown-toggle-nocaret data-toggle="dropdown" href="#dashboard"  Dashboard
        .dropdown-menu.animated.fadeIn
          a class=("dropdown-item #{'active' if controller?('dashboard')  action?('dashboard_v1')}") href="/dashboard/dashboard_v1"
            | Dashboard v1
          a class=("dropdown-item #{'active' if controller?('dashboard')  action?('dashboard_v2')}") href="/dashboard/dashboard_v2"
            | Dashboard v2
          a class=("dropdown-item #{'active' if controller?('dashboard')  action?('dashboard_v3')}") href="/dashboard/dashboard_v3"
            | Dashboard v3
      li class=("nav-item #{'active' if controller?('widgets')  action?('index')}")
        a.nav-link href="/widgets"  Widgets
    /! END Left navbar
    /! START Right Navbar
    ul.navbar-nav.flex-row
      /! START lock screen
      li.nav-item
        a.nav-link href="/pages/lock" title=("Lock screen")
          em.icon-lock
      /! END lock screen
      /! Search icon
      li.nav-item
        a.nav-link data-search-open="" href="#"
          em.icon-magnifier
      /! Fullscreen (only desktops)
      li.nav-item.d-none.d-md-block
        a.nav-link data-toggle-fullscreen="" href="#"
          em.fa.fa-expand
      /! START Alert menu
      li.nav-item.dropdown.dropdown-list
        a.nav-link.dropdown-toggle.dropdown-toggle-nocaret data-toggle="dropdown" href="#"
          em.icon-bell
          span.badge.badge-danger 11
        /! START Dropdown menu
        .dropdown-menu.dropdown-menu-right.animated.flipInX
          .dropdown-item
            /! START list group
            .list-group
              /! list item
              .list-group-item.list-group-item-action
                .media
                  .align-self-start.mr-2
                    em.fab.fa-twitter.fa-2x.text-info
                  .media-body
                    p.m-0 New followers
                    p.m-0.text-muted.text-sm 1 new follower
              /! list item
              .list-group-item.list-group-item-action
                .media
                  .align-self-start.mr-2
                    em.fa.fa-envelope.fa-2x.text-warning
                  .media-body
                    p.m-0 New e-mails
                    p.m-0.text-muted.text-sm You have 10 new emails
              /! list item
              .list-group-item.list-group-item-action
                .media
                  .align-self-start.mr-2
                    em.fa.fa-tasks.fa-2x.text-success
                  .media-body
                    p.m-0 Pending Tasks
                    p.m-0.text-muted.text-sm 11 pending task
              /! last list item
              .list-group-item.list-group-item-action
                span.d-flex.align-items-center
                  span.text-sm More notifications
                  span.badge.badge-danger.ml-auto 14
            /! END list group
        /! END Dropdown menu
      /! END Alert menu
      /! START Offsidebar button
      li.nav-item
        a.nav-link data-no-persist="true" data-toggle-state="offsidebar-open" href="#"
          em.icon-notebook
      /! END Offsidebar menu
    /! END Right Navbar
  /! END Nav wrapper
  /! START Search form
  form.navbar-form action="search.html" role="search"
    .form-group
      input.form-control placeholder=("Type and hit enter ...") type="text" /
      .fa.fa-times.navbar-form-close data-search-dismiss=""
    button.d-none type="submit"  Submit
  /! END Search form
/! END Top Navbar